name: Test-CodeBuild

on: [pull_request, push]

jobs:
  run-codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: taoyong-ty/aws-codebuild-run-build@68607d6a8379ed596627a0026061c3b9b3c88909
        with:
          project-name: aws-codebuild-run-build


