name: Test-CodeBuild

on: [pull_request, push]

jobs:
  run-codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: yamao-latte/aws-codebuild-run-build@2c66ba7ee677e4031a68bd206f5f112a975e1d96
        with:
          project-name: aws-codebuild-run-build
          source-location-override: taoyong-ty/codebuild-helloworld
